import test from'node:test';import assert from'node:assert/strict';
import{runQuery}from'../src/query/queryEngine';
import{buildTemporalRenderModel,resolveActualForecastBands,resolveActualForecastZoneShares}from'../src/query/actualForecast';
import type{ChartConfig,Dataset}from'../src/types';

const dataset:Dataset={id:'credit_lifecycle',label:'Split',description:'',fields:[{id:'date',label:'Дата',kind:'dimension',unit:'date',semantic:{businessObject:'mock',role:'date',dataType:'date',granularity:'day'}},{id:'scenario',label:'Сценарий',kind:'dimension',unit:'text',semantic:{businessObject:'mock',role:'scenario',dataType:'string',members:{FCT:{label:'Факт',timeRole:'actual'},BASE:{label:'Базовый',timeRole:'forecast'}}}},{id:'value',label:'Значение',kind:'measure',unit:'currency'}],rows:[{date:'20260601',scenario:'FCT',value:10},{date:'20260701',scenario:'BASE',value:20},{date:'20260801',scenario:'BASE',value:30}]};
const base:ChartConfig={version:1,datasetId:'credit_lifecycle',chartType:'line',viewBy:['date'],stackBy:[],metrics:[{fieldId:'value',aggregation:'SUM',yAxisId:'left'}],eventFields:[],eventCategoryVisibility:{},filters:{},seriesSettings:{},actualForecast:{enabled:true,splitMode:'date',showDivider:true,showPeriodLabels:true,forecastBackground:true,forecastLineStyle:'dashed'}};

test('date split uses strict before and inclusive forecast boundary without changing aggregates',()=>{const model=runQuery(dataset,base,{}, {splitDate:'2026-07-01'});const series=model.series[0];assert.deepEqual(model.data.map(point=>point[series.dataKey]),[10,20,30]);assert.deepEqual(model.data.map(point=>model.actualForecast?.contexts[point.categoryKey][series.dataKey].timeRole),['actual','forecast','forecast']);const render=buildTemporalRenderModel(model,model.series);const forecast=render.lines.find(line=>line.role==='forecast')!;assert.equal(render.data[0][forecast.key],10);assert.equal(model.data[0][forecast.key],undefined)});

test('field mode keeps conflicting business roles visible and reports the global boundary conflict',()=>{const config:ChartConfig={...base,actualForecast:{...base.actualForecast!,splitMode:'field',statusField:'scenario',actualValues:['FCT'],forecastValues:['BASE']}};const model=runQuery(dataset,config,{}, {splitDate:'2026-08-01'});assert.ok(model.warnings.some(warning=>warning.includes('не совпадает')));assert.equal(model.actualForecast?.contexts[model.data[1].categoryKey][model.series[0].dataKey].timeRole,'forecast');assert.equal(model.data[1][model.series[0].dataKey],20)});

test('series mode takes member roles from semantic metadata',()=>{const config:ChartConfig={...base,stackBy:['scenario'],actualForecast:{...base.actualForecast!,splitMode:'series'}};const model=runQuery(dataset,config,{}, {splitDate:'2026-07-01'});assert.deepEqual(model.series.map(series=>series.timeRole),['actual','forecast']);assert.deepEqual(model.series.map(series=>series.columnPath[0].label),['Факт','Базовый'])});

test('disabled split keeps continuous source series and produces no split model',()=>{const config:ChartConfig={...base,actualForecast:{...base.actualForecast!,enabled:false}};const model=runQuery(dataset,config,{}, {splitDate:'2026-07-01'});assert.equal(model.actualForecast,undefined);const render=buildTemporalRenderModel(model,model.series);assert.deepEqual(render.lines.map(line=>({key:line.key,role:line.role})),[{key:model.series[0].dataKey,role:'unknown'}]);assert.deepEqual(render.data,model.data)});

test('split bands keep a full visible zone when the boundary is outside the domain',()=>{const domain:[number,number]=[10,30];assert.deepEqual(resolveActualForecastBands(domain,20),{actualEnd:20,forecastStart:20,inside:true,showActual:true,showForecast:true});assert.deepEqual(resolveActualForecastBands(domain,5),{actualEnd:5,forecastStart:10,inside:false,showActual:false,showForecast:true});assert.deepEqual(resolveActualForecastBands(domain,35),{actualEnd:30,forecastStart:35,inside:false,showActual:true,showForecast:false})});

test('zone strip shares align labels with the clamped split position',()=>{const domain:[number,number]=[10,30];assert.deepEqual(resolveActualForecastZoneShares(domain,20),{actual:.5,forecast:.5});assert.deepEqual(resolveActualForecastZoneShares(domain,5),{actual:0,forecast:1});assert.deepEqual(resolveActualForecastZoneShares(domain,35),{actual:1,forecast:0})});
