import test from'node:test';import assert from'node:assert/strict';
import{isValidSplitDate,migrateDashboard,normalizeSplitDateInput}from'../src/config/dashboard';
import{DEFAULT_PAGES}from'../src/config/presets';

test('splitDate accepts only real ISO calendar dates',()=>{assert.equal(isValidSplitDate('2026-07-01'),true);assert.equal(isValidSplitDate('2026-02-31'),false);assert.equal(isValidSplitDate(null),false)});
test('split date input stays ISO after selecting a native date',()=>{assert.equal(normalizeSplitDateInput('2026-08-03'),'2026-08-03');assert.equal(normalizeSplitDateInput('20260803'),'2026-08-03');assert.equal(normalizeSplitDateInput(''),null)});
test('migrating a legacy compact splitDate normalizes it to ISO',()=>{const migrated=migrateDashboard({version:1,pages:DEFAULT_PAGES,parameters:{splitDate:'20260803'}},DEFAULT_PAGES);assert.equal(migrated.parameters.splitDate,'2026-08-03')});
test('legacy page arrays migrate with an empty required global parameter',()=>{const migrated=migrateDashboard(DEFAULT_PAGES,DEFAULT_PAGES);assert.equal(migrated.parameters.splitDate,null);assert.equal(migrated.pages.length,DEFAULT_PAGES.length)});
test('dashboard payload preserves its saved splitDate',()=>{const migrated=migrateDashboard({version:1,pages:DEFAULT_PAGES,parameters:{splitDate:'2026-07-01'}},DEFAULT_PAGES);assert.equal(migrated.parameters.splitDate,'2026-07-01')});
test('migration removes legacy splitDate page filters',()=>{const pages=structuredClone(DEFAULT_PAGES);pages[0].pageFilters=[{fieldId:'splitDate',kind:'categorical',defaultValue:['2026-07-01']} as never,{fieldId:'split-date',kind:'categorical',defaultValue:['2026-07-01']} as never];const migrated=migrateDashboard({version:1,pages,parameters:{splitDate:'2026-07-01'}},DEFAULT_PAGES);assert.deepEqual(migrated.pages[0].pageFilters,[])});
test('legacy Waterfall settings reset to the empty Bridge v2 contract',()=>{const source=structuredClone(DEFAULT_PAGES),page=source.find(item=>item.id==='pnl-waterfall')!;page.config.waterfall={bindings:{stepsField:'step_key',valueField:'value',itemTypeField:'item_type',orderField:'item_order'}} as never;const migrated=migrateDashboard({version:1,pages:source,parameters:{splitDate:'2026-07-01'}},DEFAULT_PAGES),bridge=migrated.pages.find(item=>item.id==='pnl-waterfall')!.config.waterfall!;assert.equal(bridge.version,2);assert.equal(bridge.dimensionKey,null);assert.deepEqual(bridge.items,[])});
test('waterfall widget migration repairs a stale dataset binding from the page config',()=>{const source=structuredClone(DEFAULT_PAGES),page=source.find(item=>item.id==='pnl-waterfall')!;page.widgets=[{id:'pnl-waterfall-chart',type:'chart',title:'P&L',description:'',datasetId:'writecube_fin_reports',chartConfig:{...page.config,datasetId:'writecube_fin_reports',chartType:'waterfall',waterfall:undefined},visible:true} as never];const migrated=migrateDashboard({version:1,pages:source,parameters:{splitDate:'2026-07-01'}},DEFAULT_PAGES),widget=migrated.pages.find(item=>item.id==='pnl-waterfall')!.widgets[0];assert.equal(widget.datasetId,'pnl_waterfall');assert.equal(widget.chartConfig?.datasetId,'pnl_waterfall');assert.equal(widget.chartConfig?.waterfall?.dimensionKey,'step_key')});
test('mapping demo presets cover the five basic chart types',()=>{const ids=['demo-mapping-column','demo-mapping-line','demo-mapping-pie','demo-mapping-stacked-column','demo-mapping-combo'],types=['column','line','pie','stacked-column','combo'];ids.forEach((id,index)=>{const page=DEFAULT_PAGES.find(item=>item.id===id);assert.ok(page,`missing ${id}`);assert.equal(page.config.chartType,types[index]);assert.ok(page.config.viewBy.length);assert.ok(page.config.metrics.length);assert.ok(page.header?.markdown.includes('View by'));assert.equal(page.widgets[0]?.chartConfig?.chartType,types[index])})});
test('multi-dimension mapping demo preserves ordered composite axes',()=>{const page=DEFAULT_PAGES.find(item=>item.id==='demo-mapping-multi-dimensions');assert.ok(page);assert.deepEqual(page.config.viewBy,['period','region']);assert.deepEqual(page.config.stackBy,['scenario','version']);assert.deepEqual(page.config.metrics.map(item=>item.fieldId),['revenue']);assert.deepEqual(page.pageFilters,[{fieldId:'region',kind:'categorical',defaultValue:['MSK','SPB']}]);assert.equal(page.widgets[0]?.chartConfig?.chartType,'column')});
test('migration appends missing mapping demo pages once',()=>{const legacy=DEFAULT_PAGES.filter(item=>!item.id.startsWith('demo-mapping-'));const migrated=migrateDashboard({version:2,pages:legacy,parameters:{splitDate:'2026-08-15'}},DEFAULT_PAGES);for(const id of ['demo-mapping-column','demo-mapping-line','demo-mapping-pie','demo-mapping-stacked-column','demo-mapping-combo','demo-mapping-multi-dimensions'])assert.equal(migrated.pages.filter(item=>item.id===id).length,1)});
