import React from'react';
import{Bar,BarChart,CartesianGrid,Cell,ComposedChart,Legend,Line,LineChart,Pie,PieChart,ReferenceArea,ReferenceLine,ResponsiveContainer,Tooltip as RechartsTooltip,XAxis,YAxis}from'recharts';
import type{ChartConfig,ChartEvent,ChartModel,ChartPoint,ChartSeries,Dataset,KpiCardModel,KpiModel,PointSeriesContext,SeriesTimeRole,Unit}from'../types';
import{layoutEventRows,timePosition,type EventCategoryRow,type EventCluster}from'../events/eventLayout';
import{clustersAtX,nearestTimePoint,timestampAtX}from'../events/eventInteraction';
import{buildTemporalRenderModel,resolveActualForecastBands,resolveActualForecastZoneShares}from'../query/actualForecast';
import{SMALL_MULTIPLES_SYNC_ID,smallMultiplesSyncEnabled}from'../query/smallMultiples';
import{UI_IDS,ui}from'../uiIds';
const Tooltip: any = RechartsTooltip;
import{RollingForecastChart,ThresholdComparisonChart,WaterfallChart}from'./SpecializedChartRenderers';
const fmt=(v:unknown,percent=false)=>{const n=Number(v);if(!Number.isFinite(n))return'—';return new Intl.NumberFormat('ru-RU',{notation:percent?'standard':'compact',maximumFractionDigits:percent?2:1,style:percent?'percent':'decimal'}).format(n)};
const tick=(v:unknown)=>fmt(v);
const unitTick=(unit:Unit|undefined)=>(v:unknown)=>fmt(v,unit==='percent'||unit==='ratio');
const Tip=({active,payload,label}:any)=>active&&payload?.length?<div className="builder-tooltip"><b>{payload[0]?.payload?.categoryLabel||label}</b>{payload.map((p:any)=><span key={p.dataKey}><i style={{background:p.color}}/>{p.name}: {fmt(p.value)}</span>)}</div>:null;
const displayEventDate=(date:string)=>date.length===8?`${date.slice(6,8)}.${date.slice(4,6)}.${date.slice(0,4)}`:date;
const timeTick=(value:unknown)=>{const date=new Date(Number(value));return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('ru-RU',{month:'short',year:'2-digit',timeZone:'UTC'}).format(date):String(value)};
const eventValue=(event:ChartEvent)=>fmt(event.relatedValue,event.unit==='percent'||event.unit==='ratio');
const roleLabel=(role:SeriesTimeRole)=>({actual:'Факт',forecast:'Прогноз',plan:'План',scenario:'Сценарий',unknown:'Не определено'}[role]);
const contextText=(context:PointSeriesContext|undefined)=>context?[`Тип данных: ${roleLabel(context.timeRole)}`,context.scenarioValues.length?`Сценарий: ${context.scenarioValues.join(', ')}`:'',context.versionValues.length?`Версия: ${context.versionValues.join(', ')}`:''].filter(Boolean):[];
const kpiFormat=(value:number|null,unit:Unit)=>value===null?'—':fmt(value,unit==='percent'||unit==='ratio');
const kpiDeltaColor=(card:KpiCardModel,model:KpiModel)=>{if(card.trend==='unknown'||card.trend==='flat')return model.settings.neutralColor;const positive=card.trend==='up'&&!model.settings.reverseComparisonColor||card.trend==='down'&&model.settings.reverseComparisonColor;return positive?model.settings.positiveColor:model.settings.negativeColor};
function KpiSparkline({card}:{card:KpiCardModel}){const values=card.sparkline.map(item=>item.value).filter((value):value is number=>typeof value==='number'&&Number.isFinite(value));if(values.length<2)return null;const min=Math.min(...values),max=Math.max(...values),range=max-min||1,points=values.map((value,index)=>`${(index/(values.length-1))*100},${100-((value-min)/range)*100}`).join(' ');return <svg className="kpi-sparkline" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="4" vectorEffect="non-scaling-stroke"/></svg>}
function KpiChart({model}:{model:KpiModel}){const settings=model.settings,layoutClass=`kpi-grid kpi-layout-${settings.layout} kpi-align-${settings.alignment}`;return <section {...ui('chart.kpi')} className={layoutClass} aria-label={settings.title||'KPI'}>{(settings.title||settings.note)&&<header className="kpi-panel-header">{settings.title&&<b>{settings.title}</b>}{settings.note&&<small>{settings.note}</small>}</header>}<div className="kpi-card-list">{model.cards.map(card=>{const detail=`${card.label}: текущее ${kpiFormat(card.currentValue,card.unit)}${card.currentPeriodLabel?` за ${card.currentPeriodLabel}`:''}; сравнение ${kpiFormat(card.comparisonValue,card.unit)}${card.comparisonPeriodLabel?` за ${card.comparisonPeriodLabel}`:''}; абсолютное изменение ${kpiFormat(card.absoluteDelta,card.unit)}; процентное изменение ${card.percentDelta===null?'—':`${card.percentDelta.toFixed(1)}%`}`;return <article {...ui(`chart.kpi.card.${card.id}`)} className="kpi-card" key={card.id} tabIndex={0} title={detail} aria-label={detail}><small className={`kpi-label kpi-label-${settings.labelFontSize}`}>{card.label}</small><strong className={`kpi-value kpi-value-${settings.valueFontSize}`}>{kpiFormat(card.currentValue,card.unit)}</strong>{settings.showPeriodLabel&&card.currentPeriodLabel&&<span className="kpi-period">{card.currentPeriodLabel}</span>}{settings.comparisonType!=='none'&&card.comparisonValue!==null&&<div className="kpi-delta" style={{color:kpiDeltaColor(card,model)}}>{settings.showTrendIndicator&&<b aria-hidden="true">{card.trend==='up'?'▲':card.trend==='down'?'▼':'•'}</b>}{settings.comparisonType==='percent'?`${card.percentDelta===null?'—':`${card.percentDelta>=0?'+':''}${card.percentDelta.toFixed(1)}%`}`:`${card.absoluteDelta===null?'—':`${card.absoluteDelta>=0?'+':''}${kpiFormat(card.absoluteDelta,card.unit)}`}`}</div>}{settings.showComparisonLabel&&card.comparisonValue!==null&&<span className="kpi-comparison">vs {kpiFormat(card.comparisonValue,card.unit)}{card.comparisonPeriodLabel?` · ${card.comparisonPeriodLabel}`:''}</span>}{settings.showSparkline&&<KpiSparkline card={card}/>}</article>})}</div></section>}
const lineDash=(role:SeriesTimeRole,model:ChartModel)=>role==='forecast'&&model.actualForecast?.settings.forecastLineStyle==='dashed'?'7 5':undefined;
const lineOpacity=(role:SeriesTimeRole,model:ChartModel)=>role==='forecast'&&model.actualForecast?.settings.forecastLineStyle==='solid'?0.58:1;
function ActualForecastDecorations({model,divider=true,yAxisId=0}:{model:ChartModel;divider?:boolean;yAxisId?:string|number}){const split=model.actualForecast,domain=model.timeDomain;if(!split||!domain)return null;const[,end]=domain,boundary=split.splitTimestamp,settings=split.settings,{forecastStart,inside,showForecast}=resolveActualForecastBands(domain,boundary);return <>{settings.forecastBackground&&showForecast&&<ReferenceArea {...ui(UI_IDS.actualForecast.forecastZone)} x1={forecastStart} x2={end} yAxisId={yAxisId} fill="#0f8278" fillOpacity={.07} strokeOpacity={0}/>} {divider&&settings.showDivider&&inside&&<ReferenceLine {...ui(UI_IDS.actualForecast.divider)} x={boundary} yAxisId={yAxisId} stroke="#66777d" strokeDasharray="3 4"/>}</>}
function TimeSeriesLegend({model,series}:{model:ChartModel;series:ChartSeries[]}){return <section {...ui(UI_IDS.timeSeriesLegend)} className="time-series-legend" aria-label="Легенда числовых серий"><span>Series</span><div>{series.map(item=>{const forecast=item.timeRole==='forecast',dashed=forecast&&model.actualForecast?.settings.forecastLineStyle==='dashed';return <span {...ui(UI_IDS.legendSeries(item.id))} key={item.id}><i style={{borderTopColor:item.color,borderTopStyle:dashed?'dashed':'solid'}}/><b>{item.label}</b></span>})}</div></section>}
function ActualForecastZoneStrip({model,leftInset,rightInset}:{model:ChartModel;leftInset:number;rightInset:number}){const split=model.actualForecast,domain=model.timeDomain;if(!split||!domain||!split.settings.showPeriodLabels)return null;const{actual,forecast}=resolveActualForecastZoneShares(domain,split.splitTimestamp),inside=actual>0&&forecast>0;return <div className="actual-forecast-zone-strip" style={{'--time-left-inset':`${leftInset}px`,'--time-right-inset':`${rightInset}px`}as React.CSSProperties}><div>{actual>0&&<span {...ui(UI_IDS.actualForecast.actualLabel)} className="actual-zone" style={{width:`${actual*100}%`}}>{split.settings.actualLabel||'Факт'}</span>}{forecast>0&&<span {...ui(UI_IDS.actualForecast.forecastLabel)} className={'forecast-zone '+(inside&&split.settings.showDivider?'with-divider':'')} style={{width:`${forecast*100}%`}}>{split.settings.forecastLabel||'Прогноз'}</span>}</div></div>}
function TemporalTooltip({active,payload,model,series}:any){const point=payload?.[0]?.payload as ChartPoint|undefined;if(!active||!point)return null;return <div className="builder-tooltip split-tooltip"><b>{point.categoryLabel}</b>{(series as ChartSeries[]).map(item=>{const value=point[item.dataKey],context=model.actualForecast?.contexts[point.categoryKey]?.[item.dataKey] as PointSeriesContext|undefined;if(value==null)return null;return <article key={item.id}><span><i style={{background:item.color}}/>{item.label}: {fmt(value,item.unit==='percent'||item.unit==='ratio')}</span>{contextText(context).map(text=><small key={text}>{text}</small>)}</article>})}</div>}
function SmallMultipleCursor({points,seriesId}:any){const[start,end]=points||[];if(!start||!end)return null;return <line {...ui(UI_IDS.smallMultiplesCursor(seriesId))} className="small-multiple-cursor" x1={start.x} x2={end.x} y1={start.y} y2={end.y} stroke="#0f8278" strokeWidth={1}/>}
function SmallMultipleTooltip({active,payload,label,model,series}:any){if(!active)return null;const payloadPoint=payload?.[0]?.payload as ChartPoint|undefined,point=payloadPoint||model.data.find((item:ChartPoint)=>item.timestamp===Number(label)||item.categoryLabel===String(label));if(!point)return null;const value=point[series.dataKey];return <div {...ui(UI_IDS.smallMultiplesTooltip(series.id))} className="builder-tooltip small-multiple-tooltip"><b>{point.categoryLabel}</b><span><i style={{background:series.color}}/>{series.label}: {value==null?'—':fmt(value,series.unit==='percent'||series.unit==='ratio')}</span></div>}
const TIME_SERIES_GEOMETRY={margin:{top:8,right:24,bottom:4,left:8},axisWidth:58};
const EVENT_LANE_GEOMETRY={paddingTop:7,headerHeight:21,rowHeight:44,markerCenter:15.5};
const eventPosition=(timestamp:number,domain:[number,number]|undefined)=>domain?timePosition(timestamp,domain)*100:50;
type TimeSeriesInteraction={x:number;timestamp:number;point?:ChartPoint;clusters:EventCluster[];source:'pointer'|'focus'};
const tooltipLeft=(x:number,width:number,cardWidth:number)=>x+cardWidth+20<=width?x+12:Math.max(8,x-cardWidth-12);
function LinkedValueTooltip({interaction,series,width,top,model}:{interaction:TimeSeriesInteraction;series:ChartModel['series'];width:number;top:number;model:ChartModel}){const point=interaction.point;if(!point)return null;return <div {...ui(UI_IDS.timeSeriesTooltip)} className="linked-tooltip linked-value-tooltip" role="tooltip" style={{left:`${tooltipLeft(interaction.x,width,240)}px`,top:`${top}px`}}><b>{point.categoryLabel}</b>{series.map(item=>{const context=model.actualForecast?.contexts[point.categoryKey]?.[item.dataKey];return <article key={item.id}><span><i style={{background:item.color}}/>{item.label}: {fmt(point[item.dataKey],item.unit==='percent'||item.unit==='ratio')}</span>{contextText(context).map(text=><small key={text}>{text}</small>)}</article>})}</div>}
function LinkedEventTooltip({interaction,width,height,plotHeight,plotTop}:{interaction:TimeSeriesInteraction;width:number;height:number;plotHeight:number;plotTop:number}){const events=interaction.clusters.flatMap(cluster=>cluster.events);if(!events.length)return null;return <div {...ui(UI_IDS.eventTooltip)} className="linked-tooltip linked-event-tooltip" role="tooltip" style={{left:`${tooltipLeft(interaction.x,width,260)}px`,bottom:`${Math.max(8,height-plotTop-plotHeight+8)}px`}}>{events.map(event=><article key={event.id}><b>{event.title}</b><small>{displayEventDate(event.date)} · {event.categoryLabel} · {event.documentId}</small><p>{event.comment}</p><strong>{eventValue(event)}</strong><em>Источник: lifecycle projection</em></article>)}</div>}
function EventLane({model,rows,leftInset,rightInset,onTrackMove,onMarkerFocus,onMarkerBlur}:{model:ChartModel;rows:EventCategoryRow[];leftInset:number;rightInset:number;onTrackMove:(event:React.PointerEvent<HTMLDivElement>)=>void;onMarkerFocus:(timestamp:number)=>void;onMarkerBlur:()=>void}){
 return <section {...ui(UI_IDS.eventLane)} className="time-series-event-lane" style={{'--event-left-inset':`${leftInset}px`,'--event-right-inset':`${rightInset}px`}as React.CSSProperties} aria-label="События временного ряда"><header className="event-lane-header"><b>События</b><small>{model.events.length} в диапазоне</small></header><div className="event-category-rows">{rows.length?rows.map(row=><div {...ui(UI_IDS.eventCategoryRow(row.category.key))} key={row.category.key} className="event-category-row" aria-label={`${row.category.label}: ${row.eventCount} событий`}><header className="event-category-heading"><i style={{background:row.category.color}}/><b>{row.category.label}</b><small>{row.eventCount}</small></header><div className="event-category-track" onPointerMove={onTrackMove}>{row.clusters.length?row.clusters.map(cluster=>{const first=cluster.events[0],multiple=cluster.events.length>1,descriptionId=`event-description-${cluster.id}`;return <div key={cluster.id} className="event-annotation" style={{left:`${eventPosition(cluster.timestamp,model.timeDomain)}%`,'--event-color':multiple?'#6f8294':first.color}as React.CSSProperties}><button {...ui(multiple?UI_IDS.eventCluster(cluster.id):UI_IDS.eventMarker(first.id))} type="button" className="event-marker" aria-describedby={descriptionId} aria-label={multiple?`${cluster.events.length} событий, ${row.category.label}, ${displayEventDate(first.date)}`:`${first.title}, ${row.category.label}, ${displayEventDate(first.date)}`} onFocus={()=>onMarkerFocus(cluster.timestamp)} onBlur={onMarkerBlur}><i>{multiple?cluster.events.length:''}</i></button>{cluster.showLabel&&<span className="event-label">{multiple?`${cluster.events.length} события`:first.title}</span>}<span id={descriptionId} className="event-description">{cluster.events.map(event=>`${event.title}. ${displayEventDate(event.date)}. ${event.categoryLabel}. ${event.comment}`).join(' ')}</span></div>}):<p className="event-empty">Нет событий</p>}</div></div>):<p className="event-empty">Нет подключённых категорий событий</p>}</div><div {...ui(UI_IDS.eventLegend)} className="event-legend"><span>Events</span>{model.eventCategories.map(category=><span key={category.key} className={category.visible?'':'off'}><i style={{background:category.color}}/>{category.label}</span>)}</div>{model.warnings.length>0&&<small className="event-warning">{model.warnings.join(' · ')}</small>}</section>
}
function TimeSeriesEvents({model,series,dual}:{model:ChartModel;series:ChartSeries[];dual:boolean}){
 const layoutRef=React.useRef<HTMLDivElement>(null),plotRef=React.useRef<HTMLDivElement>(null),focusTimestampRef=React.useRef<number|null>(null);const[size,setSize]=React.useState({width:0,height:0,plotHeight:0,plotTop:0}),[interaction,setInteraction]=React.useState<TimeSeriesInteraction>();
 React.useEffect(()=>{const layout=layoutRef.current,plot=plotRef.current;if(!layout||!plot)return;const update=()=>{const next={width:layout.clientWidth,height:layout.clientHeight,plotHeight:plot.clientHeight,plotTop:plot.offsetTop};setSize(current=>current.width===next.width&&current.height===next.height&&current.plotHeight===next.plotHeight&&current.plotTop===next.plotTop?current:next)};update();if(typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(update);observer.observe(layout);observer.observe(plot);return()=>observer.disconnect()},[]);
 const right=series.find(item=>item.yAxisId==='right'),left=series.find(item=>item.yAxisId==='left')||series[0],rightInset=TIME_SERIES_GEOMETRY.margin.right+(dual?TIME_SERIES_GEOMETRY.axisWidth:0),leftInset=TIME_SERIES_GEOMETRY.margin.left+TIME_SERIES_GEOMETRY.axisWidth,usableWidth=Math.max(0,size.width-leftInset-rightInset);
 const rows=React.useMemo(()=>layoutEventRows(model.events,model.eventCategories,model.timeDomain,usableWidth),[model.events,model.eventCategories,model.timeDomain,usableWidth]);
 React.useEffect(()=>{const layout=layoutRef.current;if(!layout)return;const laneHeight=EVENT_LANE_GEOMETRY.paddingTop+EVENT_LANE_GEOMETRY.headerHeight+Math.max(rows.length,1)*EVENT_LANE_GEOMETRY.rowHeight+34+(model.warnings.length?18:0);layout.style.setProperty('--time-series-plot-min-height','300px');layout.style.setProperty('--event-lane-height',`${laneHeight}px`);},[rows.length,model.warnings.length]);
 const x=(timestamp:number)=>leftInset+(model.timeDomain?timePosition(timestamp,model.timeDomain)*usableWidth:usableWidth/2);
 const activateX=(pointerX:number,source:'pointer'|'focus')=>{if(!model.timeDomain)return;const clamped=Math.min(Math.max(pointerX,leftInset),leftInset+usableWidth),timestamp=timestampAtX(clamped,leftInset,usableWidth,model.timeDomain);setInteraction({x:clamped,timestamp,point:nearestTimePoint(model.data,timestamp),clusters:clustersAtX(rows,clamped,leftInset,usableWidth,model.timeDomain),source})};
 const movePlot=(event:React.PointerEvent<HTMLDivElement>)=>activateX(event.clientX-event.currentTarget.getBoundingClientRect().left,'pointer');
 const moveLane=(event:React.PointerEvent<HTMLDivElement>)=>activateX(leftInset+event.clientX-event.currentTarget.getBoundingClientRect().left,'pointer');
 const focus=(timestamp:number)=>{focusTimestampRef.current=timestamp;activateX(x(timestamp),'focus')},leave=()=>{const timestamp=focusTimestampRef.current;if(timestamp===null)setInteraction(current=>current?.source==='pointer'?undefined:current);else activateX(x(timestamp),'focus')},blur=()=>{focusTimestampRef.current=null;setInteraction(current=>current?.source==='focus'?undefined:current)};
 const overlayTop=size.plotTop+TIME_SERIES_GEOMETRY.margin.top,crosshairHeight=Math.max(0,size.plotHeight+EVENT_LANE_GEOMETRY.paddingTop+EVENT_LANE_GEOMETRY.headerHeight+rows.length*EVENT_LANE_GEOMETRY.rowHeight-TIME_SERIES_GEOMETRY.margin.top),render=React.useMemo(()=>buildTemporalRenderModel(model,series),[model,series]),split=model.actualForecast,splitInside=Boolean(split&&model.timeDomain&&split.splitTimestamp>model.timeDomain[0]&&split.splitTimestamp<model.timeDomain[1]),bucketedAxis=model.data.some(point=>/^\d{4}(?:Q[1-4]|H[12])$/.test(String(point.categoryLabel)));
 return <div ref={layoutRef} className="time-series-layout" onPointerLeave={leave}><TimeSeriesLegend model={model} series={series}/><ActualForecastZoneStrip model={model} leftInset={leftInset} rightInset={rightInset}/><div className="event-guide-overlay" aria-hidden="true">{rows.flatMap((row,rowIndex)=>row.clusters.map(cluster=><span {...ui(UI_IDS.eventGuide(cluster.id))} key={cluster.id} className="event-guide" style={{left:`${x(cluster.timestamp)}px`,top:`${overlayTop}px`,height:`${Math.max(0,size.plotHeight+EVENT_LANE_GEOMETRY.paddingTop+EVENT_LANE_GEOMETRY.headerHeight+rowIndex*EVENT_LANE_GEOMETRY.rowHeight+EVENT_LANE_GEOMETRY.markerCenter-TIME_SERIES_GEOMETRY.margin.top)}px`}}/>))}</div>{split&&split.settings.showDivider&&splitInside&&<span {...ui(UI_IDS.actualForecast.divider)} className="actual-forecast-divider" aria-hidden="true" style={{left:`${x(split.splitTimestamp)}px`,top:`${overlayTop}px`,height:`${crosshairHeight}px`}}/>}{interaction&&<span {...ui(UI_IDS.eventCrosshair)} className="event-crosshair" data-visible="true" aria-hidden="true" style={{left:`${interaction.x}px`,top:`${overlayTop}px`,height:`${crosshairHeight}px`}}/>}<div ref={plotRef} className="time-series-plot" onPointerMove={movePlot}><ResponsiveContainer width="100%" height="100%"><LineChart data={render.data} margin={TIME_SERIES_GEOMETRY.margin}><CartesianGrid vertical={false}/><XAxis dataKey="timestamp" type="number" scale="time" domain={model.timeDomain||['dataMin','dataMax']} tickFormatter={timeTick} minTickGap={40}/><YAxis yAxisId="left" width={TIME_SERIES_GEOMETRY.axisWidth} tickFormatter={unitTick(left?.unit)}/>{dual&&<YAxis yAxisId="right" width={TIME_SERIES_GEOMETRY.axisWidth} orientation="right" tickFormatter={unitTick(right?.unit)}/>}<ActualForecastDecorations model={model} divider={false} yAxisId="left"/>{render.lines.map(line=><Line key={`${line.series.id}-${line.role}`} dataKey={line.key} name={line.series.label} stroke={line.series.color} yAxisId={dual?line.series.yAxisId:'left'} dot={false} connectNulls={false} strokeWidth={2} strokeDasharray={lineDash(line.role,model)} strokeOpacity={lineOpacity(line.role,model)}/>)}</LineChart></ResponsiveContainer></div><EventLane model={model} rows={rows} leftInset={leftInset} rightInset={rightInset} onTrackMove={moveLane} onMarkerFocus={focus} onMarkerBlur={blur}/>{interaction&&<LinkedValueTooltip interaction={interaction} series={series} width={size.width} top={overlayTop+4} model={model}/>} {interaction&&<LinkedEventTooltip interaction={interaction} width={size.width} height={size.height} plotHeight={size.plotHeight} plotTop={size.plotTop}/>}</div>
}
function TemporalLine({model,series}:{model:ChartModel;series:ChartSeries[]}){const render=React.useMemo(()=>buildTemporalRenderModel(model,series),[model,series]),leftInset=TIME_SERIES_GEOMETRY.margin.left+TIME_SERIES_GEOMETRY.axisWidth,rightInset=TIME_SERIES_GEOMETRY.margin.right;return <div className="time-renderer split-time-renderer temporal-layout"><TimeSeriesLegend model={model} series={series}/><ActualForecastZoneStrip model={model} leftInset={leftInset} rightInset={rightInset}/><div className="temporal-plot"><ResponsiveContainer width="100%" height="100%"><LineChart data={render.data} margin={TIME_SERIES_GEOMETRY.margin}><CartesianGrid vertical={false}/><XAxis dataKey="timestamp" type="number" scale="time" domain={model.timeDomain||['dataMin','dataMax']} tickFormatter={timeTick} minTickGap={40}/><YAxis width={TIME_SERIES_GEOMETRY.axisWidth} tickFormatter={unitTick(series[0]?.unit)}/><ActualForecastDecorations model={model}/><Tooltip content={<TemporalTooltip model={model} series={series}/>}/>{render.lines.map(line=><Line key={`${line.series.id}-${line.role}`} dataKey={line.key} name={line.series.label} stroke={line.series.color} dot={false} connectNulls={false} strokeWidth={2} strokeDasharray={lineDash(line.role,model)} strokeOpacity={lineOpacity(line.role,model)}/>)}</LineChart></ResponsiveContainer></div>{model.warnings.length>0&&<small className="chart-warning">{model.warnings.join(' · ')}</small>}</div>}
function SmallMultiples({model,series,config,dataset}:{model:ChartModel;series:ChartSeries[];config:ChartConfig;dataset:Dataset}){const temporal=config.viewBy.some(id=>dataset.fields.find(field=>field.id===id)?.semantic?.dataType==='date'),sync=smallMultiplesSyncEnabled(config.smallMultiplesSyncCursor,temporal);return <div className="small-multiples" data-sync-cursor={sync}>{series.slice(0,4).map(item=><article key={item.id}><b>{item.label}</b><ResponsiveContainer width="100%" height={150}><LineChart data={model.data} syncId={sync?SMALL_MULTIPLES_SYNC_ID:undefined} syncMethod={sync?'value':'index'}>{temporal?<XAxis dataKey="timestamp" type="number" scale="time" domain={model.timeDomain||['dataMin','dataMax']} hide/>:<XAxis dataKey="categoryLabel" hide/>}<YAxis hide/><Tooltip filterNull={false} content={<SmallMultipleTooltip model={model} series={item}/>} cursor={<SmallMultipleCursor seriesId={item.id}/>}/><Line dataKey={item.dataKey} name={item.label} stroke={item.color} dot={false} connectNulls={false} strokeWidth={2}/></LineChart></ResponsiveContainer></article>)}</div>}
export function ChartRenderer({model,config,dataset,onSelectRollingVintage}:{model:ChartModel;config:ChartConfig;dataset:Dataset;onSelectRollingVintage?:(date:string)=>void}){
 if(config.chartType==='rolling-forecast') console.info('[rolling-forecast] ChartRenderer', {hasModel:Boolean(model.rollingForecast), vintages:model.rollingForecast?.vintages.length ?? 0, diagnostics:model.diagnostics, warnings:model.warnings});
 if(model.diagnostics.length)return <div className="builder-state"><b>Невозможно построить график</b>{model.diagnostics.map(x=><span key={x}>{x}</span>)}</div>;
 if(config.chartType==='threshold-comparison'&&model.thresholdComparison)return <ThresholdComparisonChart model={model.thresholdComparison}/>;
 if(config.chartType==='rolling-forecast'&&model.rollingForecast)return <RollingForecastChart model={model.rollingForecast} onSelectVintage={onSelectRollingVintage}/>;
 if(config.chartType==='waterfall'&&model.waterfall)return <WaterfallChart model={model.waterfall} warnings={model.warnings}/>;
 if(config.chartType==='kpi'&&model.kpi)return <KpiChart model={model.kpi}/>;
 const series=model.series.filter(s=>s.visible);
 if(!series.length)return <div className="builder-state"><b>Все серии скрыты</b><span>Включите хотя бы одну серию в настройках дизайна</span></div>;
 if(config.chartType==='table')return <div className="detail-table"><table><thead><tr><th>Категория</th>{series.map(s=><th key={s.id}>{s.label}</th>)}</tr></thead><tbody>{model.data.slice(0,100).map(r=><tr key={r.categoryKey}><td>{r.categoryLabel}</td>{series.map(s=><td key={s.id}>{fmt(r[s.dataKey])}</td>)}</tr>)}</tbody></table></div>;
 if(config.chartType==='heatmap'){const values=model.data.flatMap(r=>series.map(s=>Number(r[s.dataKey])||0));const max=Math.max(...values,1);return <div className="heatmap"><div className="heatmap-head"/><div className="heatmap-head">Значение</div>{model.data.map(r=><React.Fragment key={r.categoryKey}><b>{r.categoryLabel}</b><div className="heat-cell" style={{'--heat':String(Math.max(...series.map(s=>Number(r[s.dataKey])||0))/max)} as React.CSSProperties}>{fmt(Math.max(...series.map(s=>Number(r[s.dataKey])||0)))}</div></React.Fragment>)}</div>}
 if(config.chartType==='bullet'){const actual=Number(model.data.at(-1)?.[series[0]?.dataKey]||0),target=Number(model.data.at(-1)?.[series[1]?.dataKey]||0),max=Math.max(actual,target)*1.25||1;return <div className="bullet"><div><span style={{width:`${target/max*100}%`}}/><i style={{left:`${target/max*100}%`}}/><b style={{width:`${actual/max*100}%`}}/></div><strong>Actual {fmt(actual,true)}</strong><small>Target {fmt(target,true)}</small></div>}
 if(config.chartType==='pie'){const s=series[0],settings=config.pie||{donut:true,innerRadiusPercent:58,labelPosition:'legend' as const,showLabels:true,showLegend:true,legendPosition:'right' as const,legendValueMode:'value-percent' as const,showTotal:true,totalLabel:'Итого',sliceLimit:5,groupRemainingAsOther:true,otherLabel:'Прочие',palette:['#6bd8cb','#b9c7e0','#ffb59a','#d27956','#3c4a5e'],paddingAngle:2},raw=model.data.map(r=>({name:r.categoryLabel,value:Number(r[s.dataKey])||0})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value),limited=settings.sliceLimit&&settings.sliceLimit>0?raw.slice(0,settings.sliceLimit):raw,rest=settings.sliceLimit&&settings.groupRemainingAsOther?raw.slice(settings.sliceLimit).reduce((sum,item)=>sum+item.value,0):0,data=rest>0?[...limited,{name:settings.otherLabel,value:rest,isOther:true}]:limited,total=data.reduce((sum,item)=>sum+item.value,0),formatLegend=(value:number)=>settings.legendValueMode==='percent'?`${Math.round(value/total*100)}%`:settings.legendValueMode==='value'?fmt(value):`${fmt(value)} (${Math.round(value/total*100)}%)`,inner=settings.donut?`${Math.max(0,Math.min(80,settings.innerRadiusPercent))}%`:0,cx=settings.legendPosition==='right'&&settings.showLegend?'36%':'50%';return <div className={`pie-renderer pie-legend-${settings.legendPosition}`} style={{'--pie-center-x':cx,'--pie-center-y':'50%'} as React.CSSProperties}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} cx={cx} cy="50%" dataKey="value" nameKey="name" innerRadius={inner} outerRadius="72%" paddingAngle={settings.paddingAngle} label={settings.showLabels&&settings.labelPosition==='inside'?((props:any)=>`${Math.round((props.value/total)*100)}%`):settings.showLabels&&settings.labelPosition==='callout'?((props:any)=>`${props.name} ${Math.round((props.value/total)*100)}%`):false} labelLine={settings.showLabels&&settings.labelPosition==='callout'}>{data.map((item,i)=><Cell key={item.name} fill={settings.palette[i%settings.palette.length]}/>)}</Pie><Tooltip formatter={(value:number)=>formatLegend(value)}/>{settings.showLegend&&<Legend layout={settings.legendPosition==='bottom'?'horizontal':'vertical'} verticalAlign={settings.legendPosition==='bottom'?'bottom':'middle'} align={settings.legendPosition==='bottom'?'center':'right'} formatter={(value)=>{const item=data.find(candidate=>candidate.name===value);return item?`${value} · ${formatLegend(item.value)}`:value;}}/>}</PieChart></ResponsiveContainer>{settings.donut&&settings.showTotal&&<div className="pie-total"><small>{settings.totalLabel||'Итого'}</small><b>{fmt(total)}</b></div>}</div>}
 if(config.chartType==='small-multiples')return <SmallMultiples model={model} series={series} config={config} dataset={dataset}/>;
 if(config.chartType==='combo'){const dual=Boolean(config.dualAxisEnabled);const axis=(s:typeof series[number])=>dual?s.yAxisId:'left';const left=series.find(s=>axis(s)==='left'),right=series.find(s=>axis(s)==='right');return <ResponsiveContainer width="100%" height="100%"><ComposedChart data={model.data}><CartesianGrid vertical={false} stroke="#e4e9e9"/><XAxis dataKey="categoryLabel" minTickGap={24}/><YAxis yAxisId="left" tickFormatter={unitTick(left?.unit)}/>{dual&&right&&<YAxis yAxisId="right" orientation="right" tickFormatter={unitTick(right.unit)}/>}<Tooltip content={<Tip/>}/><Legend/>{series.map(s=>s.seriesType==='column'?<Bar key={s.id} dataKey={s.dataKey} name={s.label} fill={s.color} yAxisId={axis(s)} opacity={.78}/>:<Line key={s.id} dataKey={s.dataKey} name={s.label} stroke={s.color} yAxisId={axis(s)} dot={false} strokeWidth={2}/>)}</ComposedChart></ResponsiveContainer>}
 if(config.chartType==='time-series-events'){const right=series.find(item=>item.yAxisId==='right'),dual=Boolean(config.dualAxisEnabled&&right);return <TimeSeriesEvents model={model} series={series} dual={dual}/>}
 if(config.chartType==='line'){const temporal=config.viewBy.some(id=>dataset.fields.find(field=>field.id===id)?.semantic?.dataType==='date');return temporal?<TemporalLine model={model} series={series}/>:<div className="time-renderer"><ResponsiveContainer width="100%" height="100%"><LineChart data={model.data}><CartesianGrid vertical={false}/><XAxis dataKey="categoryLabel" minTickGap={25}/><YAxis tickFormatter={tick}/><Tooltip content={<Tip/>}/><Legend/>{series.map(s=><Line key={s.id} dataKey={s.dataKey} name={s.label} stroke={s.color} dot={false} connectNulls={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div>}
 return <ResponsiveContainer width="100%" height="100%"><BarChart data={model.data}><CartesianGrid vertical={false}/><XAxis dataKey="categoryLabel" minTickGap={24}/><YAxis tickFormatter={tick}/><Tooltip content={<Tip/>}/><Legend/>{series.map(s=><Bar key={s.id} dataKey={s.dataKey} name={s.label} fill={s.color} stackId={config.chartType==='stacked-column'?'stack':undefined}/>)}</BarChart></ResponsiveContainer>
}
