import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BarChart3,ChartNoAxesColumn,LineChart as LineIcon,PieChart as PieIcon,Search,Database,CalendarDays,Hash,GripVertical,ChevronDown,Save,Undo2,Settings2,Eye,MoreHorizontal,Info,LockKeyhole,PanelLeftClose,Plus,Clock3,Sparkles}from'lucide-react';
import{ResponsiveContainer,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,PieChart,Pie,Cell}from'recharts';
import header from './data/report_header.json';
import rows from './data/report_data.json';
import{UI_IDS,ui}from'./uiIds';
import'./styles.css';

const COLORS=['#107f76','#263b56','#c58936','#6f8294','#925f55','#53736a','#977b9c'];
const chartTypes=[
 {id:'column',label:'Столбцы',group:'Сравнение',icon:ChartNoAxesColumn},
 {id:'line',label:'Линия',group:'Динамика',icon:LineIcon},
 {id:'pie',label:'Круговая',group:'Структура',icon:PieIcon},
 {id:'events',label:'Временной ряд + события',group:'Динамика',icon:Clock3},
 {id:'waterfall',label:'Водопад',group:'Структура',icon:BarChart3,planned:true},
 {id:'scatter',label:'Точечная',group:'Связи',icon:Sparkles,planned:true}
];

function parse(v){if(v===''||v==null)return null;const n=Number(v);return Number.isFinite(n)?n:null}
function buildModel(){const hs=header.headers;const data=rows.data;const dim=hs[0];const measure=hs[1];const leaves=measure.children||[];return{categories:data.map(r=>({key:String(r[0].value),label:r[0].label})),series:leaves.map((l,i)=>({id:`series_${i}`,dataKey:`s_${i}`,label:`Договор ${l.label}`,measureLabel:measure.label,order:i,color:COLORS[i%COLORS.length]})),data:data.map(r=>Object.assign({categoryKey:String(r[0].value),categoryLabel:r[0].label},...leaves.map((_,i)=>({[`s_${i}`]:parse(r[i+1]?.value)})))),diagnostics:{leafCount:leaves.length,rowCount:data.length,invalidCells:0},dimension:dim.label,measure:measure.label}}
const fmt=v=>v==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v);
const events=[{date:'2025',title:'Пересмотр прогноза',cat:'Прогноз'},{date:'2027',title:'Новая кредитная линия',cat:'Финансы'}];

function Bucket({uiId,title,subtitle,children,disabled}){return <section {...ui(uiId)} className={'bucket '+(disabled?'disabled':'')}><header><div><b>{title}</b><small>{subtitle}</small></div><Plus size={15}/></header>{children}</section>}
function App(){
 const model=useMemo(buildModel,[]); const [type,setType]=useState('column');const[search,setSearch]=useState('');const[dirty,setDirty]=useState(false);const[agg,setAgg]=useState('SUM');const[hidden,setHidden]=useState([]);const[tab,setTab]=useState('mapping');const[notice,setNotice]=useState('');const[showUiIds,setShowUiIds]=useState(false);
 const visible=model.series.filter(s=>!hidden.includes(s.id)); const isPie=type==='pie';
 const selectType=t=>{if(t.planned){setNotice(`${t.label}: тип запланирован и не входит в текущий mapping contract`);return}if(t.id==='pie'&&model.series.length>1){setNotice('Круговая диаграмма требует ровно одну серию. В демо будет использована первая серия.');}setType(t.id);setDirty(true)};
 const toggle=s=>{setHidden(h=>h.includes(s.id)?h.filter(x=>x!==s.id):[...h,s.id]);setDirty(true)};
 return <div {...ui(UI_IDS.app)} className="app" data-ui-inspector={showUiIds}><a {...ui(UI_IDS.skipLink)} className="skip" href="#canvas">К графику</a>
  <header {...ui(UI_IDS.topbar.root)} className="topbar"><div {...ui(UI_IDS.topbar.brand)} className="brand"><span className="brandmark"><BarChart3/></span><div><strong>EPM VISUAL</strong><small>Chart Builder</small></div></div><div {...ui(UI_IDS.topbar.breadcrumbs)} className="crumb">Рабочие книги <span>/</span> Планирование платежей <span>/</span> Визуализация</div><div className="actions"><span {...ui(UI_IDS.topbar.saveStatus)} className={'status '+(dirty?'dirty':'')}><i/>{dirty?'Не сохранено':'Сохранено'}</span><button {...ui(UI_IDS.topbar.inspector)} className={'ghost inspector-toggle '+(showUiIds?'active':'')} aria-pressed={showUiIds} onClick={()=>setShowUiIds(v=>!v)}><Settings2/>UI IDs</button><button {...ui(UI_IDS.topbar.discard)} className="ghost" onClick={()=>{setDirty(false);setNotice('Изменения сброшены')}}><Undo2/>Сбросить</button><button {...ui(UI_IDS.topbar.save)} className="primary" onClick={()=>{setDirty(false);setNotice('Конфигурация сохранена локально')}}><Save/>Сохранить</button></div></header>
  <main {...ui(UI_IDS.workspace)} className="workspace">
   <aside {...ui(UI_IDS.catalog.root)} className="catalog"><div {...ui(UI_IDS.catalog.title)} className="panel-title"><div><span>01</span><h2>Данные</h2></div><button {...ui(UI_IDS.catalog.collapse)} className="icon-button" aria-label="Свернуть каталог"><PanelLeftClose/></button></div><label {...ui(UI_IDS.catalog.source)} className="source">Источник данных<Database/><select><option>Платежи по договорам</option></select><ChevronDown/></label><div {...ui(UI_IDS.catalog.search)} className="search"><Search/><input aria-label="Поиск полей" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти поле…"/></div><div {...ui(UI_IDS.catalog.dimensions)} className="field-group"><h3>Аналитики <em>2</em></h3>{['Дата','Номер договора'].filter(x=>x.toLowerCase().includes(search.toLowerCase())).map((x,i)=><button {...ui(UI_IDS.catalog.field(i?'contract-number':'date'))} className="field" key={x}><GripVertical/><span className={i?'abc':'date'}>{i?'Abc':<CalendarDays/>}</span><b>{x}</b><MoreHorizontal/></button>)}</div><div {...ui(UI_IDS.catalog.measures)} className="field-group"><h3>Показатели <em>1</em></h3>{'Общая сумма платежа'.toLowerCase().includes(search.toLowerCase())&&<button {...ui(UI_IDS.catalog.field('total-payment'))} className="field"><GripVertical/><span className="measure"><Hash/></span><b>Общая сумма платежа</b><MoreHorizontal/></button>}</div><div {...ui(UI_IDS.catalog.help)} className="catalog-foot"><Info/><span>Поля можно перетаскивать или добавлять через меню •••</span></div></aside>
   <section {...ui(UI_IDS.canvas.root)} className="center" id="canvas"><div {...ui(UI_IDS.canvas.header)} className="canvas-head"><div><span className="eyebrow">ПЛАНИРОВАНИЕ ПЛАТЕЖЕЙ · 2024–2029</span><h1>Динамика платежей по договорам</h1><p>Платежи снижаются после 2025 года; обязательства концентрируются в договорах 0004 и 0005.</p></div><div className="canvas-tools"><button {...ui(UI_IDS.canvas.info)}><Info/>О данных</button><button {...ui(UI_IDS.canvas.more)} aria-label="Дополнительные действия"><MoreHorizontal/></button></div></div>
    {notice&&<div {...ui(UI_IDS.canvas.notice)} className="notice" role="status"><Info/>{notice}<button {...ui(UI_IDS.canvas.noticeClose)} aria-label="Закрыть уведомление" onClick={()=>setNotice('')}>×</button></div>}
    <div {...ui(UI_IDS.canvas.card)} className="chart-card"><div {...ui(UI_IDS.canvas.kpi)} className="chart-meta"><span>Общая сумма платежа</span><b>{fmt(model.data.reduce((a,r)=>a+model.series.reduce((s,x)=>s+(r[x.dataKey]||0),0),0))} <small>₽</small></b><em>7 серий · {model.data.length} периодов</em></div><div {...ui(UI_IDS.canvas.renderer(type))} className="chart-wrap">{isPie?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={model.data.filter(d=>d.s_0!=null).map(d=>({name:d.categoryLabel,value:d.s_0}))} dataKey="value" nameKey="name" innerRadius={72} outerRadius={118} paddingAngle={2}>{model.data.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={fmt}/><Legend/></PieChart></ResponsiveContainer>:type==='column'?<ResponsiveContainer width="100%" height="100%"><BarChart data={model.data} margin={{top:18,right:12,left:0,bottom:8}}><CartesianGrid vertical={false} stroke="#e5e9eb"/><XAxis dataKey="categoryLabel" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={fmt}/><Tooltip formatter={(v,n)=>[fmt(v),model.series.find(s=>s.dataKey===n)?.label||n]} contentStyle={{borderRadius:4,border:'1px solid #d9e0e2'}}/><Legend formatter={v=>model.series.find(s=>s.dataKey===v)?.label||v}/>{visible.map(s=><Bar key={s.id} dataKey={s.dataKey} fill={s.color} radius={[2,2,0,0]}/>)}</BarChart></ResponsiveContainer>:<div className="event-chart"><ResponsiveContainer width="100%" height="88%"><LineChart data={model.data} margin={{top:18,right:12,left:0,bottom:6}}><CartesianGrid vertical={false} stroke="#e5e9eb"/><XAxis dataKey="categoryLabel" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={fmt}/><Tooltip formatter={(v,n)=>[fmt(v),model.series.find(s=>s.dataKey===n)?.label||n]}/><Legend formatter={v=>model.series.find(s=>s.dataKey===v)?.label||v}/>{visible.map(s=><Line key={s.id} dataKey={s.dataKey} stroke={s.color} strokeWidth={2} dot={{r:3}} connectNulls={false}/>)}</LineChart></ResponsiveContainer>{type==='events'&&<div {...ui(UI_IDS.eventLane)} className="event-lane"><span>События</span>{events.map(e=><button {...ui(UI_IDS.eventMarker(e.date))} key={e.date} style={{left:`${16+(Number(e.date)-2024)*14}%`}} title={`${e.date}: ${e.title}`}><i/>{e.title}</button>)}</div>}</div>}</div>
     <div {...ui(UI_IDS.canvas.legend)} className="series-legend"><span>Ряды</span>{model.series.map(s=><button {...ui(UI_IDS.legendSeries(s.id))} key={s.id} className={hidden.includes(s.id)?'off':''} onClick={()=>toggle(s)}><i style={{background:s.color}}/>{s.label}</button>)}</div></div>
    <footer {...ui(UI_IDS.canvas.diagnostics)} className="canvas-foot"><span>Источник: Pivot/D3Host mock · обновлено сейчас</span><span><i className="ok"/>Модель валидна · {model.diagnostics.leafCount} leaf columns</span></footer>
   </section>
   <aside {...ui(UI_IDS.settings.root)} className="settings"><div className="tabs"><button {...ui(UI_IDS.settings.tabMapping)} className={tab==='mapping'?'active':''} onClick={()=>setTab('mapping')}>Маппинг</button><button {...ui(UI_IDS.settings.tabDesign)} className={tab==='design'?'active':''} onClick={()=>setTab('design')}>Дизайн</button></div>{tab==='mapping'?<><div {...ui(UI_IDS.settings.mappingTitle)} className="right-title"><span>02</span><div><h2>Структура графика</h2><p>Распределите поля по ролям</p></div></div><Bucket uiId={UI_IDS.mapping.bucket('view-by')} title="View by" subtitle="Категории · ось X"><div {...ui(UI_IDS.mapping.token('view-by-date'))} className="token"><CalendarDays/><span><small>Дата</small><b>Год</b></span><MoreHorizontal/></div></Bucket><Bucket uiId={UI_IDS.mapping.bucket('stack-by')} title="Stack by" subtitle="Серии · цвет"><div {...ui(UI_IDS.mapping.token('stack-by-contract'))} className="token"><span className="abc">Abc</span><span><small>Номер договора</small><b>7 элементов</b></span><MoreHorizontal/></div></Bucket><Bucket uiId={UI_IDS.mapping.bucket('metrics')} title="Metrics" subtitle="Значения · ось Y"><div {...ui(UI_IDS.mapping.token('metrics-total-payment'))} className="token metric"><button {...ui(UI_IDS.mapping.aggregation)} onClick={()=>{setAgg(agg==='SUM'?'AVG':'SUM');setDirty(true)}}>{agg}<ChevronDown/></button><span><small>Общая сумма платежа</small><b>₽ · 0 знаков</b></span><MoreHorizontal/></div></Bucket><Bucket uiId={UI_IDS.mapping.bucket('events')} title="Events" subtitle="Annotation layer"><button {...ui(UI_IDS.mapping.addEventSource)} className="add-event" onClick={()=>{setType('events');setDirty(true)}}><Plus/>Подключить источник событий</button></Bucket></>:<><div {...ui(UI_IDS.settings.designTitle)} className="right-title"><span>03</span><div><h2>Визуальное представление</h2><p>Smart Disable защищает маппинг</p></div></div><div {...ui(UI_IDS.design.chartTypes)} className="type-grid">{chartTypes.map(t=>{const I=t.icon;return <button {...ui(UI_IDS.design.chartType(t.id))} key={t.id} onClick={()=>selectType(t)} className={(type===t.id?'active ':'')+(t.planned?'planned':'')} aria-disabled={t.planned}><I/><span>{t.label}</span>{t.planned&&<em>PLANNED</em>}</button>})}</div><section {...ui(UI_IDS.design.series)} className="series-settings"><h3>Ряды <span>{visible.length}/{model.series.length}</span></h3>{model.series.map(s=><div key={s.id}><i style={{background:s.color}}/><span>{s.label}</span><button {...ui(UI_IDS.seriesSetting(s.id))} aria-label={`Показать или скрыть серию ${s.label}`} onClick={()=>toggle(s)}><Eye/></button></div>)}</section></>}</aside>
  </main></div>}
createRoot(document.getElementById('root')).render(<App/>);
