const dynamic = (prefix, key, control) =>
  [
    prefix,
    String(key)
      .toLowerCase()
      .replace(/[^a-z0-9_-]+/g, "-"),
    control,
  ]
    .filter(Boolean)
    .join(".");

export const UI_IDS = Object.freeze({
  app: "app.shell",
  skipLink: "app.navigation.skip-to-chart",
  topbar: Object.freeze({
    root: "topbar.root",
    brand: "topbar.brand",
    breadcrumbs: "topbar.breadcrumbs",
    saveStatus: "topbar.status.save",
    inspector: "topbar.action.ui-ids",
    discard: "topbar.action.discard",
    save: "topbar.action.save",
  }),
  navigation: Object.freeze({
    rail: "navigation.rail",
    home: "navigation.home",
    files: "navigation.files",
    data: "navigation.data",
    builder: "navigation.builder",
    processes: "navigation.processes",
  }),
  localeSwitcher: "app.locale-switcher",
  localeOption: (key) => dynamic("app.locale", key),
  workspace: "workspace.root",
  catalog: Object.freeze({
    root: "catalog.panel",
    title: "catalog.title",
    collapse: "catalog.action.collapse",
    toggle: "catalog.action.toggle",
    source: "catalog.source.selector",
    sourceDetail: "catalog.source.detail",
    meta: "catalog.dataset.meta",
    structure: "catalog.dataset.structure",
    search: "catalog.search",
    dimensions: "catalog.group.dimensions",
    measures: "catalog.group.measures",
    help: "catalog.help",
    field: (key) => dynamic("catalog.field", key),
    filterToggle: (key) => dynamic("catalog.filter-toggle", key),
    workspace: "catalog.workspace",
    searchEntities: "catalog.workspace.search",
    typeFilter: "catalog.workspace.type-filter",
    typeFilterSemantic: "catalog.type-filter.semantic",
    entityCard: (key) => dynamic("catalog.entity-card", key),
    semanticCard: "catalog.entity-card.semantic",
    breadcrumbs: "catalog.breadcrumbs",
    breadcrumbRoot: "catalog.breadcrumb.root",
    breadcrumbCatalog: "catalog.breadcrumb.catalog",
    breadcrumbEntity: "catalog.breadcrumb.entity",
    backToList: "catalog.back-to-list",
    detail: "catalog.detail",
    detailTab: (key) => dynamic("catalog.detail.tab", key),
    edit: "catalog.edit",
    fieldRow: (dataset, field) => dynamic("catalog.field-row", `${dataset}-${field}`),
    fieldEdit: (dataset, field) => dynamic("catalog.fields.edit", `${dataset}-${field}`),
    fieldEditor: "catalog.field-editor",
    fieldEditorClose: "catalog.field-editor.close",
    fieldEditorTitle: "catalog.field-editor.title",
    fieldEditorPhysical: "catalog.field-editor.physical",
    fieldEditorKind: "catalog.field-editor.kind",
    fieldEditorDataType: "catalog.field-editor.data-type",
    fieldEditorRole: "catalog.field-editor.semantic-role",
    fieldEditorUnit: "catalog.field-editor.unit",
    fieldEditorGranularity: "catalog.field-editor.granularity",
    fieldEditorInputFormats: "catalog.field-editor.input-formats",
    fieldEditorOutputFormat: "catalog.field-editor.output-format",
    fieldEditorTemporalKey: "catalog.field-editor.temporal-key",
    fieldEditorHierarchies: "catalog.field-editor.hierarchies",
    semanticHierarchy: (key) => dynamic("catalog.semantic.hierarchy", key),
    save: "catalog.save",
    cancel: "catalog.cancel",
    validation: "catalog.validation-summary",
  }),
  canvas: Object.freeze({
    root: "canvas.panel",
    header: "canvas.header",
    headerEdit: "canvas.header.edit",
    headerMarkdown: "canvas.header.markdown",
    headerColor: "canvas.header.color",
    headerBackground: "canvas.header.background",
    headerBackgroundTransparent: "canvas.header.background-transparent",
    headerApply: "canvas.header.apply",
    headerCancel: "canvas.header.cancel",
    headerPreview: "canvas.header.preview",
    info: "canvas.action.data-info",
    more: "canvas.action.more",
    notice: "canvas.notice",
    noticeClose: "canvas.notice.close",
    card: "canvas.chart-card",
    kpi: "canvas.kpi.total-payment",
    renderer: (type) => dynamic("canvas.renderer", type),
    legend: "canvas.legend",
    diagnostics: "canvas.diagnostics",
  }),
  settings: Object.freeze({
    root: "settings.panel",
    tabMapping: "settings.tab.mapping",
    tabDesign: "settings.tab.design",
    mappingTitle: "settings.mapping.title",
    designTitle: "settings.design.title",
    datasetSelector: "settings.dataset.selector",
    datasetMeta: "settings.dataset.meta",
  }),
  mapping: Object.freeze({
    bucket: (key) => dynamic("mapping.bucket", key),
    bucketAdd: (key) => dynamic("mapping.bucket", key, "add"),
    token: (key) => dynamic("mapping.token", key),
    aggregation: "mapping.metrics.aggregation",
    addEventSource: "mapping.events.add-source",
    series: "mapping.series-settings",
    smallMultiplesSync: "mapping.series-settings.small-multiples-sync",
    specializedBucket: (key) => dynamic("mapping.specialized", key),
    pageFilters: "mapping.page-filters",
    pageFiltersAdd: "mapping.page-filters.add",
    filterToggle: (key) => dynamic("mapping.filter-toggle", key),
    hierarchyToggle: (key) => dynamic("mapping.viewby", key, "hierarchy-toggle"),
  }),
  design: Object.freeze({
    chartTypes: "design.chart-types",
    chartType: (key) => dynamic("chart-type", key),
    dualAxis: "mapping.series-settings.dual-axis",
  }),
  pageFilters: Object.freeze({
    root: "page-filter.panel",
    toolbar: "page-filter.toolbar",
    reset: "page-filter.reset",
    splitDate: "page-filter.split-date",
    control: (key) => dynamic("page-filter", key),
    remove: (key) => dynamic("page-filter-remove", key),
    rangeStart: (key) => dynamic("page-filter", key, "from"),
    rangeEnd: (key) => dynamic("page-filter", key, "to"),
    scope: (key) => dynamic("page-filter", key, "scope"),
  }),
  actualForecast: Object.freeze({
    root: "mapping.actual-forecast",
    enabled: "mapping.actual-forecast.enabled",
    mode: "mapping.actual-forecast.mode",
    statusField: "mapping.actual-forecast.status-field",
    divider: "chart.actual-forecast.divider",
    forecastZone: "chart.actual-forecast.forecast-zone",
    actualLabel: "chart.actual-forecast.label.actual",
    forecastLabel: "chart.actual-forecast.label.forecast",
  }),
  timeSeriesLegend: "chart.legend.time-series",
  legendSeries: (key) => dynamic("legend.series", key),
  seriesSetting: (key, control = "visibility") =>
    dynamic("series-setting", key, control),
  metricSetting: (key, control) => dynamic("metric-setting", key, control),
  eventLane: "event.lane",
  eventLegend: "event.legend",
  eventCrosshair: "event.crosshair",
  eventTooltip: "event.tooltip",
  timeSeriesTooltip: "chart.tooltip.time-series",
  smallMultiplesCursor: (key) => dynamic("chart.small-multiples.cursor", key),
  smallMultiplesTooltip: (key) => dynamic("chart.small-multiples.tooltip", key),
  threshold: Object.freeze({
    root: "mapping.threshold-comparison",
    zones: "mapping.threshold-comparison.thresholds",
    direction: "mapping.threshold-comparison.direction",
    chart: "chart.threshold-comparison",
    summary: "chart.threshold-comparison.summary",
    marker: (key) => dynamic("chart.threshold-comparison.marker", key),
    bracket: "chart.threshold-comparison.bracket",
  }),
  rolling: Object.freeze({
    root: "mapping.rolling-forecast",
    horizon: "mapping.rolling-forecast.horizon",
    unit: "mapping.rolling-forecast.unit",
    forecastDataset: "mapping.rolling-forecast.forecast-dataset",
    actualDataset: "mapping.rolling-forecast.actual-dataset",
    mode: "mapping.rolling-forecast.mode",
    chart: "chart.rolling-forecast",
    summary: "chart.rolling-forecast.summary",
    marker: (key) => dynamic("chart.rolling-forecast.marker", key),
    targetMarker: (key) => dynamic("chart.rolling-forecast.target-marker", key),
    summaryField: (key) => dynamic("chart.rolling-forecast.summary", key),
  }),
  waterfall: Object.freeze({
    root: "mapping.waterfall",
    summary: "mapping.waterfall.summary",
    settingsOpen: "mapping.waterfall.settings-open",
    dialog: "mapping.waterfall.dialog",
    dialogClose: "mapping.waterfall.dialog.close",
    dialogCancel: "mapping.waterfall.dialog.cancel",
    dialogApply: "mapping.waterfall.dialog.apply",
    editor: "mapping.waterfall.editor",
    dimension: "mapping.waterfall.dimension",
    defaultMeasure: "mapping.waterfall.default-measure",
    sequence: "mapping.waterfall.sequence",
    sequenceRow: (key) => dynamic("mapping.waterfall.sequence-row", key),
    action: (key) => dynamic("mapping.waterfall.action", key),
    measure: (key) => dynamic("mapping.waterfall.measure", key),
    reorder: (key, direction) =>
      dynamic("mapping.waterfall.reorder", key, direction),
    addItem: "mapping.waterfall.add-item",
    validateCheckpoints: "mapping.waterfall.validate-checkpoints",
    tolerance: "mapping.waterfall.tolerance",
    chart: "chart.waterfall",
    item: (key) => dynamic("chart.waterfall.item", key),
    label: (key) => dynamic("chart.waterfall.label", key),
    connector: (key) => dynamic("chart.waterfall.connector", key),
    terminal: (key) => dynamic("chart.waterfall.terminal", key),
    reconciliation: (key) => dynamic("chart.waterfall.reconciliation", key),
    reconciliationSummary: "chart.waterfall.reconciliation-summary",
    reconciliationSummaryRow: (key) => dynamic("chart.waterfall.reconciliation-summary-row", key),
    showReconciliationSummary: "mapping.waterfall.show-reconciliation-summary",
    help: (key) => dynamic("mapping.waterfall.help", key),
  }),
  eventMarker: (key) => dynamic("event.marker", key),
  eventCluster: (key) => dynamic("event.cluster", key),
  eventGuide: (key) => dynamic("event.guide", key),
  eventCategoryRow: (key) => dynamic("event.category-row", key),
  eventCategory: (key) => dynamic("event.category", key),
  builder: Object.freeze({
    presetRail: "builder.preset-rail",
    pageSelector: "builder.page.selector",
    widgetAdd: (key) => dynamic("builder.widget-add", key),
    preset: (key) => dynamic("builder.preset", key),
    validation: "builder.validation",
    chart: "builder.chart",
    localEngineStatus: "builder.local-engine-status",
    field: (key) => dynamic("builder.field", key),
    chartType: (key) => dynamic("builder.chart-type", key),
    eventsConnect: "builder.events.connect",
    eventsDisconnect: "builder.events.disconnect",
  }),
});

export const ui = (id) => ({ "data-ui-id": id });
export const UI_ID_PATTERN = /^[a-z0-9_-]+(?:\.[a-z0-9_-]+)+$/;
